// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2026/5/13 10:10:04
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/lizhenhu/Desktop/zhihe-0508-4/plant-care-guide/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/lizhenhu/Desktop/zhihe-0508-4/plant-care-guide/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/lizhenhu/Desktop/zhihe-0508-4/plant-care-guide/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/lizhenhu/Desktop/zhihe-0508-4/plant-care-guide/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/lizhenhu/Desktop/zhihe-0508-4/plant-care-guide/plugins/**/*.{js,ts,mjs}","/Users/lizhenhu/Desktop/zhihe-0508-4/plant-care-guide/composables/**/*.{js,ts,mjs}","/Users/lizhenhu/Desktop/zhihe-0508-4/plant-care-guide/utils/**/*.{js,ts,mjs}","/Users/lizhenhu/Desktop/zhihe-0508-4/plant-care-guide/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/lizhenhu/Desktop/zhihe-0508-4/plant-care-guide/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/lizhenhu/Desktop/zhihe-0508-4/plant-care-guide/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/lizhenhu/Desktop/zhihe-0508-4/plant-care-guide/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;