// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2026/5/12 10:50:38
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/lizhenhu/Desktop/zhihe-0508-4/calendar-event-planner/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/lizhenhu/Desktop/zhihe-0508-4/calendar-event-planner/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/lizhenhu/Desktop/zhihe-0508-4/calendar-event-planner/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/lizhenhu/Desktop/zhihe-0508-4/calendar-event-planner/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/lizhenhu/Desktop/zhihe-0508-4/calendar-event-planner/plugins/**/*.{js,ts,mjs}","/Users/lizhenhu/Desktop/zhihe-0508-4/calendar-event-planner/composables/**/*.{js,ts,mjs}","/Users/lizhenhu/Desktop/zhihe-0508-4/calendar-event-planner/utils/**/*.{js,ts,mjs}","/Users/lizhenhu/Desktop/zhihe-0508-4/calendar-event-planner/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/lizhenhu/Desktop/zhihe-0508-4/calendar-event-planner/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/lizhenhu/Desktop/zhihe-0508-4/calendar-event-planner/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;